### ISSUE TITLE
Merge monsterbrain work

### ISSUE THREAD

**Issue by brospars** [brospars/simple-calendar#14]
Hi @monsterbrain ,

I wish to merge your awesome work on displaying events and the demo page but their is to many changes and some unwanted changes. What I would want is :

- Displaying events (cf screenshot and code)
- Demo page with examples
- Select callback
- Standalone (no added librairies)

I think I could cherry pick some of your work to new branches and create new PRs from that branches. 

What do you think ?

**Events :**
Events are an array of event (based on [iCal standard](https://en.wikipedia.org/wiki/ICalendar#Technical_specifications) if possible, even if we don't support the whole thing)
```js
events: [
  {
    summary: string
    dateStart: timestamp
    dateEnd: timestamp
  },
  ...
]
```

![image](https://user-images.githubusercontent.com/5736114/73277254-2bba3e00-41ea-11ea-8387-7d42ea137efa.png)

**Comment by monsterbrain** [comment]
Thanks. I really liked your library, used in one of my projects, added features that later got added.

And yes my work differed a lot in many ways, you can extract whichever features you want. I'll help with that.

And regarding events, if the start and end date is mentioned, should it be shown as a line extending all along the dates ? Would it make it complex, such that, the name 'Simple Calender' is no longer there ;) ?

**Comment by brospars** [comment]
Yeah you are right. We need to keep things simple. 
I'll will support `dateStart` and `dateEnd` but only display a dot on each day this event lasts. Also I prefer the syntax with array of objects rather than 2 arrays.

**Comment by monsterbrain** [comment]
Ok. I understand. I'm a bit confused on where to add the code ? In my repository or could you add as a collaborator ? Or Is it possible to fork your master branch into a separate branch into my forked repository ?

**Comment by brospars** [comment]
I'm currently working on it. I'm doing it manually and will credit you.
