### ISSUE TITLE
 [IMPORTANT] Month change issue  

### ISSUE THREAD

**Issue by LeeHM** [brospars/simple-calendar#15]
1. 2020-01-30 
2. 2021-01-29
3. 2022-01-29
4. 2023-01-29
5. 2024-01-30

Change JAN to FEB so updated MAR check your code !

thanks!

**Comment by brospars** [comment]
Sorry I don't understand what is the problem. Could you elaborate please ?

**Comment by LeeHM** [comment]
@brospars 

If you move on from January to February, it will be March.

**Comment by valerio-bozzolan** [comment]
To be honest it's impossible to understand your problem from your message, anyway note that months in JavaScript start from zero. That's why January is `0` and Febrary is `1` etc. Is this your problem?

**Comment by brospars** [comment]
Could you provide a simple example to reproduce it (Codepen or Jsfiddle) ?
