### ISSUE TITLE
how to keep calendar open on selection of date?

### ISSUE THREAD

**Issue by Faisal-nfl** [brospars/simple-calendar#16]

**Comment by brospars** [comment]
Hi,
could you elaborate please ? Do you mean keeping the calendar open between refreshes ?

**Comment by Faisal-nfl** [comment]
I meant black screen appears with cross button on date selection.
I don't want to show this, just want to know that which date selected & keep calendar as it is.

**Comment by monsterbrain** [comment]
You mean something like this ?

![image](https://user-images.githubusercontent.com/10105094/76451367-4ee52980-63f5-11ea-97f1-e5fdea28b1a7.png)

**Comment by brospars** [comment]
I see.. What @Faisal-nfl needs is the event `onDateSelect` to be fired even when event details are disabled.
I'm changing it right now, so will have to update and do something like this :  
```js
$("#container").simpleCalendar({
   // ...
   disableEventDetails: true,
   onDateSelect: function (date) {
       console.log(date)
   },
   // ...
}
```

**Comment by Faisal-nfl** [comment]
thanks, just to let you know  onDateSelect event is working but still black screen appears.
for now I have to comment these lines.
```
$(plugin.element).on('click', '.day', function (e) {
        var date = new Date($(this).data('date'));
        var events = plugin.getDateEvents(date);
        // if (!$(this).hasClass('disabled')) {
        //   plugin.fillUp(e.pageX, e.pageY);
        //   plugin.displayEvents(events);
        // }
        plugin.settings.onDateSelect(date, events);
      });
```
