### ISSUE TITLE
Question: Ability to add Events?

### ISSUE THREAD

**Issue by valerio-bozzolan** [brospars/simple-calendar#17]
Hello!

Just a question. Is it possible to update Events after initialization?

I tried calling again `$calendar.simpleCalendar( { events: myEvents } )` but without much success, but maybe I'm doing something wrong.

Thank you :)

**Comment by valerio-bozzolan** [comment]
P.S.

Inspecting the source code I've found this undocumented way that seems to work:

```
$calendar.data('plugin_simpleCalendar').settings.events = myEvents;
```

A very ugly workaround I think.

**Comment by brospars** [comment]
Yes I wanted to implements methods to add or access events. PR welcome !

**Comment by edcaron** [comment]
Ugly workaround 

```
$("#calendar").simpleCalendar().data('plugin_simpleCalendar').settings.events =  [ ];

var currentDate = $("#calendar").simpleCalendar().data('plugin_simpleCalendar').currentDate;
var calendar    = $("#calendar").find('.calendar');

$("#calendar").simpleCalendar().data('plugin_simpleCalendar').buildCalendar(currentDate, calendar);
```

**Comment by AidosMarcos** [comment]
Any news about this development? 
The workaround talked here does not work, data('plugin_simpleCalendar') gives me undefined.

I need to update displayed event depending of a user choice.

Any way to update calendar, or destroy instance and initiate again?

**Comment by monsterbrain** [comment]
I've added a new PR with the above mentioned adding event functionality. @AidosMarcos @brospars

**Comment by brospars** [comment]
Close by #32
