### ISSUE TITLE
Is this library still relevant today ?

### ISSUE THREAD

**Issue by brospars** [brospars/simple-calendar#2]
I made this library some years ago and never updated it. I don't use it often but I could work on it if someone is interested...

Todo : 

- [ ] Implementing events
- [ ] Add options and api to customize usage and controls
- [ ] Better docs and use cases
- [ ] Refactor

**Comment by monsterbrain** [comment]
Hi. I stumbled across this, as I was looking for a simple, easy to use yet elegant calendar. The other calendars (after a quick search) were quite complicated (At first sight I guess). And I usually never go through the inside mechanics of a Jquery library, but this one was small and was easy to modify, if any need to add some modifications need to be done.

Cutting short, I'm now using this, in our inhouse office app, to show the attendance of the employees, their absent / half-day leave marks etc.

I think [Kommune3's Fork](https://github.com/Kommune3/simple-calendar) has an event option added. Have to check it out.

**Comment by brospars** [comment]
Cool ! I'll check how he implemented it.
Feel free to suggest any feature you'd like and PR

**Comment by monsterbrain** [comment]
pardon me for interrupting. But How can i get an instance of the plugin, in case I need to update the values on month change. I tried assigning to variable and calling var.simpleCalendar.function() but did not work. Any help would be appreciated..
