### ISSUE TITLE
Disble event details popup

### ISSUE THREAD

**Issue by macgadger** [brospars/simple-calendar#20]
Hi

I like this plugin so much. Can you please add an option to disable Event details popup and one more can you tell me  how i can get event date selected on onEventSelect, I hope you reply soon

Thanks for awssome plugin btw

**Comment by brospars** [comment]
Hello,
It's missing from the readme but you can use `disableEventDetails: true` to disable it.

On event select, you can use `$(this).data('event')` to access event data.
