### ISSUE TITLE
Missing month navigation

### ISSUE THREAD

**Issue by marfig2005** [brospars/simple-calendar#27]
Hi,
it looks like month navigation is missing in the current version of the code.
At least, this part is suspicious:

`var calendar = $('<div class="calendar"></div>');
      var header = $('<header>' +
        '<h2 class="month"></h2>' +
        '<a class="simple-calendar-btn btn-prev" href="#"></a>' +
        '<a class="simple-calendar-btn btn-next" href="#"></a>' +
        '</header>');`

There seems to be missing "<" and ">" .. as it was in some previous version. Or maybe it's solved now differently, but when I download the current version and open index.html, month navigation buttons are missing.

Thank you
Martin

**Comment by marfig2005** [comment]
Ha :)
class seems to be wrong, instead of calendar-btn simple-calendar-btn should be used. Could you please verify?

Thanks
Martin

**Comment by brospars** [comment]
Hi, I fixed it in the last commits yesterday. Did you retry it ?

**Comment by marfig2005** [comment]
Hi, it works now, thank you
Regards
Martin
