### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by antonhilman** [brospars/simple-calendar#29]
heres my event, is't correct format?
events: [
 
 {
startDate: 2020-08-05,
endDate: 2020-08-10,
summary: 'lorem ipsum 1'
}
,
{
startDate: 2020-08-07,
endDate: 2020-08-10,
summary: 'lorem ipsum 2'
}
,
{
startDate: 2020-08-09,
endDate: 2020-08-09,
summary: 'lorem ipsum 3'
}
 ],

**Comment by brospars** [comment]
Events are inserted using `new Date()` (equivalent to `Date.parse()`). This function require a date string (you need to add quotes) and it's recommended to use the ISO format. More info [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Objets_globaux/Date/parse).

**Comment by brospars** [comment]
Closing since no update.
