### ISSUE TITLE
Persian (Shamsi) calendar

### ISSUE THREAD

**Issue by husin-sajjadi** [brospars/simple-calendar#34]
Great work, thank you for your library
Is there any feature to have a Persian (Shamsi) Calendar in this library?

**Comment by brospars** [comment]
I know nothing about this calendar but PR are welcome. Is this radically different from a gregorian calendar ?

**Comment by husin-sajjadi** [comment]
Yes, It's different. You can see that via Wikipedia:
https://en.wikipedia.org/wiki/Jalali_calendar

**Comment by brospars** [comment]
Ok I don't have time to do it myself but feel free to open a PR
