### ISSUE TITLE
reset calendar

### ISSUE THREAD

**Issue by buzi** [brospars/simple-calendar#38]
great plugin!
is it possible to reset the calendar event data ?
i tried using this
`calendar.empty().simpleCalendar({})`
but it simply disappears and doesnt load again.

**Comment by brospars** [comment]
This should work : 
```js
calendar.empty().data('plugin_simpleCalendar', null).simpleCalendar()
```
`data` is added to the container to prevent multiple instantiation that could mess up events handling.

**Comment by buzi** [comment]
Thank you. it works perfectly.
 another question if you dont mind, is there a way to initialize the calendar to a specific month other than the current date ?

**Comment by brospars** [comment]
No but this should be simple to implement. Feel free to open a PR otherwise I'll take a look when I have some spare time.
