### ISSUE TITLE
Better demo page

### ISSUE THREAD

**Issue by brospars** [brospars/simple-calendar#4]
Add examples of differents configs and usages with events

**Comment by monsterbrain** [comment]
I've made some modifications and added the event handling (basic one), but still usable I guess.

You can check it out here. 
https://monsterbrain.github.io/simple-calendar/
Main js file is not updated yet.

**Comment by brospars** [comment]
Nice ! 
I'm still working on adding events support (based on iCalendar) but a demo page like this is what I'm looking for

**Comment by findelallc** [comment]
The plugin is still useful on today's era,who wants simple integration,can we have option to add disabled dates? as I see a relevant class is added - `.wrong-month`
Requirement is simple,I would like to show all dates of a month disabled unless it's not in the event list array unlike now showing enabled all the dates.

`$("#event-cal-container").simpleCalendar({
//disabled : true,//this feature we are looking for
events: ['2019-03-04', '2019-03-08', '2019-03-12', '2019-03-15'],
eventsInfo: ['John\'s Birthday', 'Janet\'s Marriage','Graduation Day', 'Final Exams !'],
selectCallback: function(date){
  console.log('date selected '+date);
},
insertCallback: function(date){
  //console.log('date selected '+date);
}
});`

**Comment by brospars** [comment]
I'm not actively maintaining this project but feel free to create a PR and I will merge it quickly.

**Comment by monsterbrain** [comment]
@findela : If what i understand is correct, you want to disable the current month days, where there is no events.

![chrome_LxB25p71hA](https://user-images.githubusercontent.com/10105094/73235584-065f0d00-41b5-11ea-87ce-9d5bd000e3ef.png)

This can be done easily by modifying the code like

```
$("#event-cal-container").simpleCalendar({
                enableOnlyEventDays: true, // only enable event days
                fixedStartDay: false, ....
```

inside jquery.simple-calendar.js

add to plugin defaults 

```
var pluginName = "simpleCalendar",
        defaults = {
            months: ....
            enableOnlyEventDays: false, // only enable event days
           ....
        };
```

added disabled class for non-event, in-this-month days

```
                       if (eventIndex !== -1) {
                            td.find(".day").addClass("event");
                        } else if(plugin.settings.enableOnlyEventDays) {
                            // disable the non event days (of this month)
                            if (day.getMonth() == fromDate.getMonth()) {
                                td.find(".day").addClass("disabled");
                            }
                        }
```

added style for class disabled, to make it different from wrong month
```
.calendar .day.disabled {
      background: rgb(240, 240, 240);
      color: rgb(182, 182, 182); }
  .calendar .day.disabled:hover{
    border: none;
  }
```

Hope that's what you want :)

**Comment by findelallc** [comment]
thanks @monsterbrain and @brospars both of you,this code surely I will try. but I was able to modify as per my requirements,the main js code was so simply written, that can be altered.

**Comment by brospars** [comment]
Nice work @monsterbrain . The opposite could be a valid option too, to disable dates that are already taken. I'm moving this to a new issue #13 .
